apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
  namespace: default
data:
  POSTGRES_HOST: udagram.chhkyawtabqg.us-east-1.rds.amazonaws.com
  JWT_SECRET: Th1s1sR4nd0mS3cr3t
  POSTGRES_DB: postgres
  AWS_BUCKET: my-s3-bucket-udacity
  AWS_REGION: us-east-1
  AWS_PROFILE: default
  URL: http://localhost:8100
